### ISSUE TITLE
Bug: Saved game sometimes gets corrupt

### ISSUE THREAD

**Issue by hnejfnvjojgrogjwm** [ainslec/adventuron-issue-tracker#102]
Saved game sometimes gets corrupt, making loading game impossible. 
Unfortunately at the moment I can't provide more details to help isolating this bug, apart for the fact that sometimes the saved game doesn't work and the player is unable to load saved game. This happened to me in different browsers, with local game and in server game. It happened to another developer too.

I report it even without any helpful details just because this is a A class issue and needs to be addressed asap.

Please keep adding info to this issue as you manage to find out more details. I will do it too.

**Comment by ainslec** [comment]
Hello,

Terribly sorry about this elusive issue, You are right that it is a class A issue.

To address this, beta 45 adds in additional logging for loading saved games, so if this occurs, please press (in chrome or edge):

CONTROL + SHIFT + I (letter I (eye))

Then go to the CONSOLE tab of the debug window, and see if you can copy and paste the recent error messages that start with the text :

"Loading State :"

These logs could be quite long, so beware of that. If so, copy and paste into a text file, then zip and then email them to me (not posting my email address here).

Please note that beta 45 does not change the save / load game logic at all, but it does give me more diagnostic information to help track it down. Thank you for your help.

**Comment by ainslec** [comment]
Hello,

Thanks to my new logging, I have resolved this bug, but it will be a little while before I can update Adventuron. Please hold tight.

Chris

**Comment by ainslec** [comment]
The bug was triggered when the "cycle" command is executed (It corrupted the game state). As a temporary workaround, see if you can avoid using cycle (comment out the blocks and replace possibly with execute_one_at_random instead (this does not have a bug).

**Comment by ainslec** [comment]
I uploaded the (probably) fixed version of Adventuron here (beta 46):

https://adventuron.io/beta/

Please give it a try. Existing saves will not work unfortunately.

**Comment by hnejfnvjojgrogjwm** [comment]
Apparently it doesn't work in the regular Adventuron version (ATM Beta 45d), but it is fixed in beta version (Beta 48).
I said "apparently" because as it is kind of random issue it will require of further testing before confirming that is fixed.

**Comment by ainslec** [comment]
I'm 99% sure it's fixed now, but keep an eye on it. I'll hold the issue open for a few weeks.

**Comment by ainslec** [comment]
Closing this as believe this is now fixed. If there is an ongoing issue, will re-open.
