### ISSUE TITLE
Update: Please implement new and more accurate Spanish translations for system messages

### ISSUE THREAD

**Issue by hnejfnvjojgrogjwm** [ainslec/adventuron-issue-tracker#118]
Some of the system messages for Spanish are not very well translated. Please implement the new translations attached in a txt document.

[traducción adventuron.txt](https://github.com/ainslec/adventuron-issue-tracker/files/4914184/traduccion.adventuron.txt)

Please notice that some sysmess are not present in the list. For me is difficult to know which messages are still missing, but for example, the saving messages are:

[en] Load game
[spa] Juego De Carga
Please change to:
[spa] Cargar juego

[en] Return To Game (Do Nothing)
[spa] Regresar Al Juego (Hacer Nada)
Please change to:
[spa] Volver al juego (no hacer nada)

[en] Are you sure you wish to wipe the current game and load from slot (n)?
[spa] ¿Estás Seguro De Que Deseas Terminar El Juego Actual y Cargar Desde La Ranura (n)?
Please change to:
[spa] ¿Estás seguro de que deseas terminar el juego actual y cargar desde la ranura (n)?

[en] Cancelled Load
[spa] Cancelado carga
Please change to:
[spa] Carga cancelada

[en] Overwrite Contents of Save Slot (n)?
[spa] ¿Sobreescribir Los Contenidos De Guardar Ranura (n)?
Please change to:
[spa] ¿Sobreescribir el contenido guardado en la ranura (n)?

**Comment by ainslec** [comment]
Thanks so much.

Please state that you place this translations into the public domain, and I will update.

**Comment by hnejfnvjojgrogjwm** [comment]
Do use my translations the way you prefer. I already shared it with another developer.

Please provide the full list of system messages missing in the txt doc.

**Comment by ainslec** [comment]
Sorry to be pedantic, but can you reply with

"I am happy to place the supplied translations in the public domain."

**Comment by hnejfnvjojgrogjwm** [comment]
I am happy to place the supplied translations in the public domain. Now and in the future, and this applies to translations, graphics, code, and anything that benefits the development of Adventuron.

**Comment by ainslec** [comment]
Thank you for the clarification, I have made the changes, and they will go into beta 53.

**Comment by hnejfnvjojgrogjwm** [comment]
Please notice that I mentioned the system messages related to saving game as an example. I have no way to know which other messages are there. Please provide a full list of system messages to translate.
