### ISSUE TITLE
Bug: Clicking on words that include marks and special characters can result in error.

### ISSUE THREAD

**Issue by hnejfnvjojgrogjwm** [ainslec/adventuron-issue-tracker#119]
```
start_at = my_location

//language=spanish

locations {
   my_location : location "You are in a room with Jim, Ben and a stone. \n-Jim, take that 'stone' -says Ben." ;}

on_command {
   :match"ex jim"{
      :print"A very handsome guy.";}
   :match"ex stone"{
      :print"A very rocky stone.";}
}
```

Steps to reproduce:
1. Run the code provided.
2. Type "ex jim" and "ex stone" and observe the results.
2. Type just "ex" and in the location description, click on "Jim" or "stone", two words that are included in the vocabulary and therefor clickable.
3. Observe the result.

The words are reproduced in the input line as:
-Jim
'stone'
Therefore the parser will fail to recognise those words.

Moreover, please notice that the word between single quotation mark " ' " is recognised when the game language is set to English but not in Spanish.

**Comment by ainslec** [comment]
Fixed in 52c. Please confirm.

**Comment by hnejfnvjojgrogjwm** [comment]
Fixed. Please close.
