### ISSUE TITLE
Bug: LOCK after graphic doesn't work after loading game

### ISSUE THREAD

**Issue by hnejfnvjojgrogjwm** [ainslec/adventuron-issue-tracker#122]
The command LOCK after graphic in the settings doesn't work when loading game, either autatically (returning to the game when the game is in a server) or manually (selecting the LOAD option).

```
start_at = my_location

locations {
   my_location : location "You are in a room with Jim." ;}

on_command {
}
assets {
   graphics {
   my_location: jpeg "http://roboscape.co.uk/r2019.screens/loc_casa_main.jpg";
}}

themes {
   theme {
         theme_settings {
         layout= H- SEP "adv_line_cyan" G LOCK D O
}}}
```

Steps to reproduce:
1. Run the code provided
2. Type anything until the screen is full and have to scroll
3. Save game
4. Load game
5. Observe the results

**Comment by ainslec** [comment]
This is fixed.
