### ISSUE TITLE
Feature: Please implement the use of "it" suffix for Spanish language

### ISSUE THREAD

**Issue by hnejfnvjojgrogjwm** [ainslec/adventuron-issue-tracker#123]
In the Spanish language, when you replace a noun for "it", like in "grab stone and examine it", that "it" can have different forms and it goes together with the verb in one single word.

The endings can be:
-la
-lo
-mela
-melo

Examples:
[en] grab stone and examine it
[spa] coger piedra y examinarla
(verb examinar + la)

[en] grab tomato and eat it
[spa] coger tomate y comermelo
(verb comer + melo)

Moreover, there is a very small chance that some word ended in -la or -lo may cause conflict. I believe the chance is very small, but just in case I would suggest to leave it up to the developer to disable this feature.

**Comment by ainslec** [comment]
UPDATE: Added this concept into the language master interface, along with the Spanish language suffixes. Not yet made the parser aware how to use this metadata.

**Comment by ainslec** [comment]
Please test in beta 59.

https://adventuron.io/beta


// COGER PIEDRA Y EXAMINARLA

```
start_at = lakeside
language = spanish
locations {
   lakeside       : location "You are by the side of a lake.";
   forest         : location "You are in a forest." ;
}
connections {
   from, direction, to = [
      lakeside, east,  forest, 
   ]
}
objects {
   piedra   : object  "piedra" at = "lakeside" msg = "HOLA!" ;
}

```

**Comment by hnejfnvjojgrogjwm** [comment]
It works as intended.

**Comment by ainslec** [comment]
Closing this issue.
