### ISSUE TITLE
Ident graphic is not working (when using jpeg or png graphic types - non embedded)

### ISSUE THREAD

**Issue by ainslec** [ainslec/adventuron-issue-tracker#143]
Assuming the URL used by JPEG below is replaced with a valid URL, the following is not working ....

(raised by Ricardo O)

```
start_at = my_location

locations {
   my_location : location "You are in a room." ;
}

game_settings {
   ident_graphic=logo_small
   ident_graphic_horz_percent=100
   }

assets {
   graphics {
      logo_small: jpeg "some_url";
   }
```

**Comment by ainslec** [comment]
Please try this again in the new beta version (press F5).

**Comment by hnejfnvjojgrogjwm** [comment]
It doesn't work, no graphic is displayed, neither mine ( http://roboscape.co.uk/logo_small.jpg ) nor the adventuron classroom.

**Comment by hnejfnvjojgrogjwm** [comment]
Fixed. Please close.
