### ISSUE TITLE
Bug: Old saved progress loaded from updated versions of the game often creates issues

### ISSUE THREAD

**Issue by hnejfnvjojgrogjwm** [ainslec/adventuron-issue-tracker#148]
I noticed that little changes in the code sometimes do not have effect on old saved progress. But when you load an old saved file from an updated game with major changes, it often creates bugs in game.

This applies as well to the automatic save/load position that happens when the game is in a server, you quit and you return to the page.

Please, either do not allow to load old saved progress into updated code (maybe using the game_version number for control) or display a message recommending the player to start a fresh new game.

**Comment by furroy** [comment]
i ran into this as well

**Comment by ainslec** [comment]
The official way around this is to increment the following setting if you change things radically (change room names, change object names, remove objects, remove rooms):

This should not happen much after release at all, but may regularly happen during beta testing.

Incrementing the compatibility version will wipe out prior saves, but it will ensure the game is not loaded in such a way that the game is broken.

NOTE: Additive changes (new logic, new objects, new variables) will (generally speaking) not be a problem. It's only destructive changes that causes compatibility issues.

```
game_information {
   compatibility_version = 2
}
```

**Comment by hnejfnvjojgrogjwm** [comment]
This bug was fixed long ago. Please close.
