### ISSUE TITLE
Bug: In a location without exits, when the player checks the exits the response is an empty line

### ISSUE THREAD

**Issue by hnejfnvjojgrogjwm** [ainslec/adventuron-issue-tracker#164]
Place the player in a room without exits.
Run the game and type "exits".
Observe the results: A empty line is displayed.

Please implement a message like "There are no visible exits".
Please implement for Spanish the message:
No hay salidas visibles.

![no_exits](https://user-images.githubusercontent.com/65968239/95000319-be9c4b00-05b7-11eb-9d63-60e14ee158e4.jpg)

**Comment by ainslec** [comment]
Please try again ( adventuron.io/beta ).

**Comment by hnejfnvjojgrogjwm** [comment]
Fixed. Please close.
