### ISSUE TITLE
bug: it is not possible to bypass TAKE ALL

### ISSUE THREAD

**Issue by hnejfnvjojgrogjwm** [ainslec/adventuron-issue-tracker#178]
```
start_at = my_location

locations {

   my_location : location "You are in a room." ;
}

on_command{
   :match"take all"{
         :print"What do you mean by 'all'???";}
   :match"take key"{
      :if(adjective1_is"red"){
         :print"It is too hot to touch it.";}}
}

objects {
   green_key:object"a green key" start_at="my_location";
   red_key:object"a red key" start_at="my_location";
}
```
Steps to reproduce:
-Run the code provided
-Type TAKE THE RED KEY
-Observe the result: the code bypasses the normal behaviour and the key is not taken
-Type TAKE ALL
-Observe the result: Unlike the previous command, this one is not bypassed despite the fact that there is a line for this purpose.

**Comment by ainslec** [comment]
Take all overrides everything else.

To disable the default ALL mappings, use the following settings:

I have added some (brief) documentation for this here : https://adventuron.io/documentation/cookbook.html#disableall

```
game_settings {
   enable_standard_all_behaviour = false
}
```

**Comment by hnejfnvjojgrogjwm** [comment]
I am afraid that is a too radical solution for me, as I will like to have ALL available in all the other situations. It is just one specific situation in which I would like to override it.

**Comment by ainslec** [comment]
You can manually wire up the all handlers yourself too (by default adventuron includes this code by default at the top of the on_command section) but via the "enable_standard_all_behaviour = false" setting, you can place the all handlers where you like.

```
game_settings {
   enable_standard_all_behaviour = false
}

on_command {
   :match"take all"{
         :print"What do you mean by 'all'???";
         : done;
   }
   : match "take all" {
      : do_all "current_location_objects";  
   }

   : match "drop all" {
      : do_all "inventory_notworn";
   }

   : match "wear all" {
      : do_all "inventory_notworn";
   }

   : match "remove all" {
      : do_all "inventory_worn";
   }
}
```
