### ISSUE TITLE
Minor feature: Include space bar as a "continue" key

### ISSUE THREAD

**Issue by hnejfnvjojgrogjwm** [ainslec/adventuron-issue-tracker#184]
Please include the space bar as a "continue" key, for when the game uses press_any_key. For now I think it only works with Enter and mouse buttons.
Cheers.

**Comment by hnejfnvjojgrogjwm** [comment]
Bump! Please allow me to bring up this old issue because I think it is serious. To this day I still hit the space bar from time to time, it seems so natural to me, only to realize that it doesn't work. And I am pretty sure that happens to many players too.

**Comment by ainslec** [comment]
Added setting (in beta 77):

```
game_settings {
   anykey_behaviour = anykey
}
```

This will allow any key to be used for pressing any key. This does however have an impact of buffering the next command.
