### ISSUE TITLE
definite() and d() do not automatically capitalise the first word in a sentence

### ISSUE THREAD

**Issue by warrigal24** [ainslec/adventuron-issue-tracker#247]
The new definite() function does not capitalise 'the' if it's the first word in the sentence. It probably isn't smart enough to know when it's the start of a sentence, so it probably needs a separate function to do this. Perhaps cap_definite().

Similarly, d() does not capitalise the indefinite article if it's the first word in the sentence. It probably needs a separate function to do this. Perhaps cap_d().

**Comment by warrigal24** [comment]
Here's an example of the sort of thing I mean:
```
   // Clean
   : match "clean *" {
      : disambiguate_s1 "present";
      : if (!is_present(s1())) {
         : print {(not_present)}
         : done;
      }
      : print {(definite(d(s1())) + " {is_or_are} not dirty.")}
      : done;
   }
```
And here's some sample responses:
```
>CLEAN MRS
Mrs Claus is not dirty.

>WIPE TABLE
the table is not dirty.

>WASH DISHES
the dishes are not dirty.
```
Tsk,tsk. Not good enough Mr adventure author.

**Comment by ainslec** [comment]
first_cap() has been added.
