### ISSUE TITLE
camel() should be title()

### ISSUE THREAD

**Issue by warrigal24** [ainslec/adventuron-issue-tracker#248]
The camel() function is used to convert a string to title case. The term 'camel' is incorrect. Camel case is actually something quite different. It's when the first letter of each word is capitalised in a string that doesn't have any spaces between the words. This is normally used in programming. For example, 'TheAdventuronUserGuide' is camel case, whereas 'The Adventuron User Guide' is title case. Adventuron's camel() does the latter. The vast majority of the community does not know what camel case is, so don't know to search for that term.

**Comment by ainslec** [comment]
In beta 66m, it has been renamed to title_case().
