### ISSUE TITLE
Translation: Sound on / off requires a re-translation for Spanish

### ISSUE THREAD

**Issue by hnejfnvjojgrogjwm** [ainslec/adventuron-issue-tracker#249]
At the moment the Spanish translation is:

[en] sound on / off
[spa] sonar on / off

Please change to:

[spa] sonido activado / desactivado

If possible please keep "on / off" as synonyms of "activado / desactivado" as they are used in Spanish too.

Moreover, when you type sound on or off in Spanish, you got the messages:
Sound activado.
Sound desactivado.

Please implement the Spanish translation of the word "sound" in this string.

**Comment by ainslec** [comment]
Please try beta 66o.

**Comment by hnejfnvjojgrogjwm** [comment]
It is half fixed. Now it works when I type sonido on/off. But the message displayed still shows the word "sound" untranslated.
![image](https://user-images.githubusercontent.com/65968239/103919683-3d010f80-5108-11eb-872e-28e9fa2212df.png)

**Comment by ainslec** [comment]
Please try the new version.

**Comment by hnejfnvjojgrogjwm** [comment]
![image](https://user-images.githubusercontent.com/65968239/103964543-9a6e7e00-5153-11eb-90ef-890080f46125.png)

Almost there... Almost.

**Comment by hnejfnvjojgrogjwm** [comment]
This is fixed now. Please close.
