### ISSUE TITLE
Game locks up if you enter a verb followed by an article

### ISSUE THREAD

**Issue by warrigal24** [ainslec/adventuron-issue-tracker#263]
This seems to be consistent. Run a game in the editor and type a verb followed by an article such as 'a', 'an', 'some' or 'the'. The game locks up and you have to start again.

The same thing happens in a compiled game. This is serious.

**Comment by warrigal24** [comment]
After a bit of experimenting, I think I've tracked it down to `experimental_new_parser = true` in `game_settings{}`. If this is set to false, or commented out, everything behaves as usual. No lockup.

**Comment by ainslec** [comment]
Fixed in beta 66q.
