### ISSUE TITLE
Bug: The parser makes a confusing reading of certain questions

### ISSUE THREAD

**Issue by hnejfnvjojgrogjwm** [ainslec/adventuron-issue-tracker#266]
In a Spanish set game, if the player types the Spanish equivalent of "What happens?" (qué pasa) as a sentence that you can ask to a character (e.g. ASK JIM WHAT HAPPENS) Adventuron parser makes a strange reading of this sentence:
-"qué" is an adjective and goes at the beginning of the sentence. It doesn't get registered.
-"pasa" is a verb, and it is labelled as verb AND noun.

```
language=spanish
start_at = my_location

locations {
   my_location : location "You are in a Spanish room." ;
}

vocabulary {
   :verb {aliases=[pasa]}
   :adjective {aliases=[qué]}
}
```

-Please execute the code provided
-Set DEBUG ON.
-Type "qué pasa"
-Observe the result.

![image](https://user-images.githubusercontent.com/65968239/104222496-4a850500-543a-11eb-8714-6da0e8c3b306.png)

**Comment by ainslec** [comment]
I'll need a full example of the code to really know how this fits in the full sentence structure.  Parsing full colloquial sentences is kind of beyond the adventuron parser. It can only really pick out words in categories. Adding "why" as an adverb, and using the new parser might be an option. 

I need to know how all this works with the long sentence form and short sentence form together.

```
language=spanish
start_at = my_location

game_settings {
   experimental_new_parser  = true
   experimental_new_scoping = true
}

locations {
   my_location : location "You are in a Spanish room." ;
}

vocabulary {
   :verb {aliases=[pasa]}
   :adverb {
      aliases=[qué]
      //command_verb = true
   }
}

on_command {
   
   : match "pasa _"  {
      : print "Match" ;
      
   }
   
}
```

**Comment by hnejfnvjojgrogjwm** [comment]
I wrote a very long message with explanations and examples and all to add to this issue, before I realised that there are adverbs in Adventuron (where they always there?) and those question words are actually adverbs (why are they considered as adjectives too? It is a mystery to me). I think that the adverbs cover perfectly fine for what I need.

Sorry for the waste of time.

I feel silly.

**Comment by hnejfnvjojgrogjwm** [comment]
Hey! This can be closed. It was not an issue at all.
