### ISSUE TITLE
"Unwear"(quitar) and "drop"(dejar) show rare messages in spanish language. 

### ISSUE THREAD

**Issue by THEFARLANDER** [ainslec/adventuron-issue-tracker#272]
When you type verbs "quitar" and "dejar" without a noun, this happens...

![Captura de pantalla 2021-01-20 a las 18 27 25](https://user-images.githubusercontent.com/72342129/105214684-9cbbd980-5b50-11eb-94fb-15a3a88c921d.png)

It does not happen in English...
![Captura de pantalla 2021-01-20 a las 18 30 28](https://user-images.githubusercontent.com/72342129/105214887-ddb3ee00-5b50-11eb-9001-4babaa038ad5.png)

It is not an important issue, but looks like a bug for the player...
Tested on Beta 66w.

**Comment by ainslec** [comment]
Please check out beta 66x,

**Comment by THEFARLANDER** [comment]
![Captura de pantalla 2021-01-20 a las 23 06 09](https://user-images.githubusercontent.com/72342129/105247032-6b550500-5b74-11eb-8006-a0306f806fd6.png)
"Dejar" (drop) not yet fixed...

**Comment by ainslec** [comment]
Please can you check this again?

**Comment by THEFARLANDER** [comment]
Fixed in beta 66z. Please close this issue. Thanks.
