### ISSUE TITLE
[Enhancement] Add has_moved() property

### ISSUE THREAD

**Issue by warrigal24** [ainslec/adventuron-issue-tracker#274]
I am trying to replicate a feature in Inform so that I can utilise it in Crowther & Woods' original Adventure. Essentially, I need to determine if an object has ever been moved. Inform has a `moved` attribute for this. This is a Boolean property. It defaults to false. If an object is initially carried or worn, it is set to true. If an object is taken, it is set to true. Thus, you can tell whether an object has ever been taken or held by testing its `moved` attribute. In Adventuron, this would be called `has_moved`.

In 'Santa's Trainee Elf', I replicated this using a custom Boolean property. In original Adventure, there are 15 treasures and it is very cumbersome to create and test 15 custom Boolean properties. In both cases, the Boolean property is used to test whether a treasure has been moved, so that it is only scored once. (In both cases, the treasure is scored once when you initially get it and again when you drop it in the treasure room.)

Here is a small code fragment to show how it would be used in 'Santa's Trainee Elf':
```
: if (is_present "coal") {
   : match "get coal" {
      : if (!has_moved "coal") {
         : add var = "score" value = "5";
      }
   }
}
```
Here is a small code fragment to show how it would be used in a more generic manner in original Adventure:
```
: match "get _" {
   : disambiguate_s1 "present" with_trait = "treasure_t";
   : if (!has_moved (s1())) {
      : add var = "score" value = "2";
   }
}
```

**Comment by ainslec** [comment]
`has_taken "object_id" `

... added in beta 66y.
