### ISSUE TITLE
[Enhancement] Add initial property for objects

### ISSUE THREAD

**Issue by warrigal24** [ainslec/adventuron-issue-tracker#275]
I am trying to replicate the functionality of a feature in Crowther & Woods original Adventure whereby an object can have a long description when it is initially found and is not included in the object list, but has a normal short description and is included in the object list after it has been taken for the first time.

This feature was often used in Infocom games and is implemented using the `initial` property in Inform. This works as follows:
- The `initial` property is optional. You don't have to use it, unless you want to.
- The `initial` property is a string or a routine that prints a string.
- If an object has an `initial` property and the object hasn't been moved (tested using the `has_moved()` property proposed in issue #274), the string is printed after the room description and before the list of other objects.
- If an object doesn't have the `initial` property or it has been moved, the string is not printed and the object is included in the list of objects as it is now.

Here is an example of how it would appear in original Adventure:
```
You are inside a building, a well house for a large spring.
There are some keys on the ground here.
There is tasty food here.
There is a shiny brass lamp nearby.
There is an empty bottle here.

>GET ALL EXCEPT LANTERN
set of keys: Taken.
tasty food: Taken.
small bottle: Taken.

>DROP ALL
small bottle: Dropped.
tasty food: Dropped.
set of keys: Dropped.

>LOOK
You are inside a building, a well house for a large spring.
There is a shiny brass lamp nearby.
You can also see a set of keys, some tasty food and a small bottle here.
```

**Comment by ainslec** [comment]
Please try, in beta 66y ...

```
start_at = lake

locations {
   forest : location "You are in the forest.";
   lake   : location "You are by the lake.";
}

connections {
   from, direction, to = [
      lake, south, forest, 
   ]
}

objects {
   rope : object "a rope"
      at = "lake"
      experimental_initial_message = "A rope is on the floor."
   ;
   
   rock : scenery "a heavy rock" at = "lake";
   lamp : object  "a dusty lamp" at = "lake";
}
```

**Comment by ainslec** [comment]
Closed

**Comment by THEFARLANDER** [comment]
Great feature!! Thanks Chris and Garry!!
