### ISSUE TITLE
Oxford comma in items listing in room

### ISSUE THREAD

**Issue by bjbest60** [ainslec/adventuron-issue-tracker#278]
I'd like to be able to use the Oxford comma in the list of objects in a room.  I'm playing with object_list_final_separator, but it isn't quite working.  I'd like the sentences to be "You see a book and a lamp" if there are two items, and "You see a book, a lamp, and an apple" if there are three or more.  It looks like object_list_final_separator gets applied universally, so I if I change it to ", and" I wind up with "You see a book, and a lamp" if there are only two items.
Sample code:
```
start_at = start
start_theme = my_theme

locations {
   start : location "Starting room.";
}

objects {
   lamp : object "a lamp" at = "start";
   book : object "a book" at = "start";
   apple : object "an apple" at = "start";
}

themes {
   my_theme : theme {
      system_messages {
         object_list_end_text                           = .
         object_list_final_separator                    = , and\s
         object_list_header                             = You see :\s
         object_list_header_verbose                     = You see\s
         object_list_separator                          = ,\s
      }
      
   }
}
```

**Comment by ainslec** [comment]
Fixed, oxford comma is now used by default (as it should have been anyway). To disable oxford comma, use oxford_comma=false in lister_objects{} and lister_inventory {}
