### ISSUE TITLE
[FEATURE]  item_has_trait  function

### ISSUE THREAD

**Issue by nww02** [ainslec/adventuron-issue-tracker#328]
I'm trying to use traits to solve some problems as there's no other way just now, but I'm always falling back to hard-coding choices.  I'd like to be able to scan the location  or another location or player inventory for items with a certain trait and do something with them...  

For a simple example, imagine if there's a monkey that steals anything foody in your inventory:-

```
traits
{
    t_food : trait;
}

objects {
     coin : object "A gold coin"
     banana : object "A banan" traits="t_food";
  }


subroutine
{
     monkey_steals_food : subroutine {
        :experimental_scan "inventory"{
        if (item_has_trait "t_food") {
            :print {( "The monkey steals the "+item() )};
            :destroy {(item())};                    <- Note that this doesn't work either
        }
      }
}


locations{
       monkey_tree : location "The monkey tree"
      {
   on_describe {
         :if (linger() == 0) { :gosub "monkey_steals_food"; }
         }
    }
}

```

**Comment by nww02** [comment]
Another thing you can do is to check to see if sufficient numbers of items are in a place by counting items with traits.
Or you can calculate a score by adding 10 points for every piece of treasure in the treasure room,  
or unblock a bridge based on the number of weights on a  drawbridge pressure plate...
Or design a better listing function based on traits of items to generate dynamic adjectives.
.
.

**Comment by ainslec** [comment]
Related to #242

**Comment by ainslec** [comment]
This doesn't work on the web version of Adventuron (but should).

NOTE: If uncomment, print "Hello --";, then it works. This seems like a problem with the asynchronous iterator.

```
start_at = monkey_tree

traits {
    t_food : trait;
}

objects {
   coin : object "A gold coin" at = "inventory" ;
   spoon : object "A spoon" at = "inventory" ;
   banana : object "A banana" traits="t_food" at = "inventory";
}

booleans {
   is_item_food : dynamic_boolean {(has_trait { subject -> (item()) trait = "t_food" })}
}


locations{
   monkey_tree : location "The monkey tree" {
      on_describe {
         : experimental_scan "inventory"{
            //: print "Hello --";
            
            : if (is_item_food) {
               :print {( "The monkey steals the "+item() )};
               :destroy { entity -> ( item() ) }
            }
         }
      }
   }
}
```

Difference between desktop and web version is iteration order (hashmap implementation). The async lookahead is the likely culprit. Using an : if (true) {} wrapper seems to trigger a positive first scan in the expermental scan. Need to debug this.

The following works on web and desktop:

```
start_at = monkey_tree

traits {
    t_food : trait;
}

objects {
   coin : object "A gold coin" at = "inventory" ;
   spoon : object "A spoon" at = "inventory" ;
   banana : object "A banana" at = "inventory" {
      traits="t_food" 
   }
}

booleans {
   is_item_food : dynamic_boolean {(has_trait { subject -> (item()) trait = "t_food" })}
}

locations{
   monkey_tree : location "The monkey tree" {
      on_describe {
         : experimental_scan "inventory"{
            //: print "Hello --";
            : if (true) {
               : if (is_item_food) {
                  :print {( "The monkey steals the "+item() )};
                  :destroy { entity -> ( item() ) }
               }
            }
         }
      }
   }
}
```

**Comment by nww02** [comment]
Thanks,
    I was trying to work out the syntax for "has_trait", but just couldn't work out how to format the command from the error message.  Thanks for the code, I'll hold off using traits until either the below works, or the item_has_trait is implemented.  Thanks again,
Nick




________________________________

**Comment by ainslec** [comment]
Added in upcoming beta 69.

```
start_at = my_location

locations {
   my_location : location "You are in a room." ;
}

objects {
   puddle : scenery "a puddle"at = "my_location" traits = "t_wet";
   spoon  : object "a spoon" at = "my_location" ;
}

traits { t_wet : trait; }

on_startup {
   : print "Wet things :" ;
   : experimental_scan "current_location" {
      : if (item_has_trait "t_wet") {
         : print {(item())}
      }
   }
   : press_any_key ;
}
```
