### ISSUE TITLE
[BUG?]  is_just_entered_zone  doesn't accept a zone name

### ISSUE THREAD

**Issue by nww02** [ainslec/adventuron-issue-tracker#330]
I've just tried to use :-

:if (is_just_entered_zone "ship_zone") .....

in on_tick() to detect when I've just stepped aboard (or beamed aboard) the ship, and to use it to change some settings (theme) accordingly, but the parser tells me "implicit collection not permitted here.  Alternatives [character, zone]".

If I use (is_in "ship_zone"), that works just fine, but I just want to know when I enter the zone, I know I can use a boolean and write some logic to workaround it right now, so it's low priority.   Not sure if it's me doing something daft or not.

**Comment by ainslec** [comment]
This should work but does not:

```
start_at   = lakeside

locations {
   lakeside    : location "You are by the side of a lake.";
   my_location : location "You are in a room." ;
}

connections {
   from, direction, to = [
      lakeside, east, my_location, 
   ]
}

zones {
   
   my_zone : zone {
      locations  = [ my_location ]
   }
   
}

on_tick {
   
   : if (is_just_entered_zone "my_zone") {
      : print "Hello" ;
      
   }
   
}
```

**Comment by nww02** [comment]
indeed, it throws up that the zone isn't a zone, same for me.  The boolean workaround to remember whether you're in the zone or not DOES work, though, so it's not critical.
N.


________________________________

**Comment by ainslec** [comment]
Fixed in beta 70.
