### ISSUE TITLE
[FEATURE/QUERY]  override "get all"

### ISSUE THREAD

**Issue by nww02** [ainslec/adventuron-issue-tracker#331]
The way that GET ALL is implemented is ingenious, but there are occasions when you might want to change the format of the output to the user, or do some checking before "getting all".   

I tried to override it with a match, but this didn't work.

![image](https://user-images.githubusercontent.com/46803513/110468275-fad85800-80cf-11eb-8740-a6d49ebdcc3d.png)

Is it possible to override "get all" in adventuron at the moment?

**Comment by ainslec** [comment]
If you specify "enable_standard_all_behaviour = false" in game_settings{} then you have to wire up the all handlers manually, and this gives you an opportunity to intercept them.

```
start_at = my_location

game_settings {
   enable_standard_all_behaviour = false
}

locations {
   my_location : location "You are in a room." ;
}

objects {
   spoon : object "a spoon" at = "inventory" ;
   knife : object "a knife" at = "inventory" ;
   hat   : object "a hat" at = "inventory" initially_worn = "true" ;
   gloves   : object "some gloves" at = "inventory" initially_worn = "true" ;
   boulder : scenery "a boulder" at = "my_location" ;
}

on_command {
   
   : match "wear all"  {
      : do_all "inventory_notworn_wearable";
   }
   
   : match "remove all"  {
      : do_all "inventory_worn";
   }
   
   : match "get all"  {
      : do_all "current_location_objects";
   }
   
   : match "drop all"  {
      : print "TRYING TO DROP ALL ...." ;
      : do_all "inventory_notworn";
      : print "This will not execute" ;
   }

}
```

**Comment by nww02** [comment]
Brilliant! That's perfect, thanks! 🙂

________________________________

**Comment by nww02** [comment]
Brilliant! That's perfect, thanks! 🙂

As you can see, the "get all" and "get _" have different formatting... Thanks for the pointer! :)

![image](https://user-images.githubusercontent.com/46803513/110473337-51e12b80-80d6-11eb-92f9-80cf90dc5b60.png)

**Comment by nww02** [comment]
Interestingly, have you ever noticed the inconsistency in who is the adventurer in these old games?   So many books talk about whether YOU are the adventurer, or you're CONTROLLING the adventurer, but I wonder if they ever noticed that the line was even more blurred than they imagined: 
![image](https://user-images.githubusercontent.com/46803513/110474079-27dc3900-80d7-11eb-8551-7c2f6ddf0aa6.png)
