### ISSUE TITLE
[QUERY] Programmatically determining conspicuousness.

### ISSUE THREAD

**Issue by nww02** [ainslec/adventuron-issue-tracker#332]
To emulate the particular style of L9 I have to create my own object list subroutine.  This is great, until I find a scenery item or a non-conspicuous item which I may not want to print out.

is there anything analogous to:-

```
:if (is_conspicuous{object->(item())}) 
  { 
     :print {("I see a " + item())}; 
  }
:if (is_scenery{object->(item())})
 {
   :print {("I see some scenery: " + item())};
 }

```

**Comment by ainslec** [comment]
The following internal traits can be tested with has_trait {} (internal traits don't start with the t_ prefix) :

- conspicuous
- known
- has_existed
- taken
- examined
- exists
- wearable
- worn
- treasure
- immovable (IMPORTANT: this is used for scenery internally)
- character

Code snippets which may help:

```
booleans {
   is_item_conspicuous : dynamic_boolean {( has_trait { subject -> (item()) trait = "conspicuous" } )}
   is_item_scenery : dynamic_boolean {( has_trait { subject -> (item()) trait = "immovable" } )} /* internally scenery is immovable */
}

//// Your code here

:if (is_item_conspicuous)  { 
     :print {("I see a " + item())}; 
}
: else_if (is_item_scenery) {
   :print {("I see some scenery: " + item())};
}
```

**Comment by nww02** [comment]
That's perfect! Worked like a charm, thank you 🙂

Are you considering making the internal traits public?   Having these in a wiki on the advanced area of the docs would be great, I don't think the auto-complete tells you what the traits are anywhere to find out for yourself.



________________________________

**Comment by ainslec** [comment]
I tend to leave things undocumented that I haven't decided on fully. That also explains items that don't autocomplete.

Internal traits are almost ready to be documented and I'll probably use my sample code from this issue in the documentation.

**Comment by ainslec** [comment]
Documented these traits, closing this issue.
