### ISSUE TITLE
[FEATURE] Give treasure a score value

### ISSUE THREAD

**Issue by nww02** [ainslec/adventuron-issue-tracker#358]
In many games, the collection of treasure gives a different amount of score.   A crown may be worth 50, while a diamond worth 500.  

Currently, the treasure_score needs to be calculated by hand by going through every item in the player's inventory or the treasure room and then by some logic, having a giant if_then  structure e.g.  
```
for each treasure "IF I have the Crown THEN increment SCORE by 50".. and so on.
```

It would be nice if there was a function to get the current "treasure score" based on something calculated automagically, in the same way the count works in treasure_hunt mode.   For example

```

objects {
      crown : object "a golden crown"  treasure="true"  score="50"  at="treasure_room";
}

treasure_room = treasure_room;

locations {
     treasure_room : location "The treasure vault";
 }

on_command {
   :match "score *"
   {
        :print "You are carrying, or have stored in the vault, treasure to the score of " +treasure_score();
   }
}

```

This would allow us to either put the treasure score up in the banner at the top of the screen, or keep it silently in the background for printing when requested, or upon death as part of the overall score.

As usual, the score would be based upon the treasure either being in the inventory OR in the treasure room, exactly as the treasure_hunt mode's count works, but weighting the sum by the score for each piece of treasure.

In the above, if you typed in "score" you'd get the score of 50 printed, as the crown is on the floor in the treasure room.

Would also have to check if the treasure is in a container IN the the inventory / treasure room!!!

**Comment by nww02** [comment]
Here's an example of how I've done it...  I use a subroutine to calculate it based on the manual addition of some traits. It means one trait per score value...

![image](https://user-images.githubusercontent.com/46803513/111641464-1856a180-87f5-11eb-9ce4-71b19d4e6e6d.png)

This works, but isn't too elegant.

**Comment by ainslec** [comment]
Maybe use stats?

Setup the stat:
```
stats {
   stat_score : stat;
}
```

Assign the score to the object using the on_startup {} hook:

```
   spoon : object "a spoon" at = "inventory"   {
      on_startup {
         : set_stat stat = "stat_score" value = "5";
      }
   }
```

**Comment by nww02** [comment]
Yes, that's a good workaround.  Trades some coding on each object... I'll have to document that at some point..  It'd be nice to do it without code, but that works for now :)

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ainslec** [comment]
Going to close this, a treasure score is a really niche thing that is not very common, and can be worked around using existing system trait (_treasure) and a fairly easy stat based system.
