### ISSUE TITLE
Synonyms  and game_type verb_noun

### ISSUE THREAD

**Issue by basinbasin** [ainslec/adventuron-issue-tracker#365]
Beta 68j

Porting over an old Quilled game.

I have prepositions in the vocabulary which causes an error. I can either comment them out, or can add 

game_type = verb_noun at the top of the game settings

If I do that, synonyms / aliases seem to stop working. 

As an example, I have to examine a bathroom cabinet as part of the game...

Defined in the vocabulary as:

 : word { aliases = [ "bath", "cabi" ] ua      = [ "bath", "cabi" ] }
 
EXAM BATH yields the correct response.
EXAM CABI gives an incorrect generic response.
OPEN CABI gives an 'Unknown noun - "cabi".' response.
OPEN BATH gives a "You can't do that." response.

**Comment by ainslec** [comment]
Closing this, as quill games are not meant to be used in verb noun mode, the "workaround" is to port the game more fully to Adventuron. We have already discussed how to do this.
