### ISSUE TITLE
[BUG]  Split on a single-character string fails.

### ISSUE THREAD

**Issue by nww02** [ainslec/adventuron-issue-tracker#382]
I have a command tokeniser that splits the player's input based on the space character.
![image](https://user-images.githubusercontent.com/46803513/114199081-e47e2000-994b-11eb-82e9-1ae903b768b4.png)

If the last item in the list is a single character, that item is omitted:- 

![image](https://user-images.githubusercontent.com/46803513/114200292-f7452480-994c-11eb-971f-9e25cef18e4f.png)

But as you can see, multi-character words at the end of the list are picked up fine:-
![image](https://user-images.githubusercontent.com/46803513/114200347-062bd700-994d-11eb-8252-aa921bde3ee6.png)

I'm also finding that when there's only a single character, that's not tokenised either, so it seems like the last element in the list, however long it is, is omitted if it's 1 char long.

![image](https://user-images.githubusercontent.com/46803513/114200460-23f93c00-994d-11eb-9ef9-28fc0ee924b5.png)

**Comment by ainslec** [comment]
Testing with this ...

```
start_at = my_location

locations {
   my_location : location "You are in a room." ;
}

collections {
   list : list ;
}

on_startup {
   : split text = "T" sep = "\s" result = "list";
   : iterate "list" {
      : print ("ITEM: " + item());
   }
   : press_any_key ;
}
```

**Comment by ainslec** [comment]
Fixed in beta 72a.
