### ISSUE TITLE
[BUG] Compass system_message stops try_move working (beta 72c)

### ISSUE THREAD

**Issue by nww02** [ainslec/adventuron-issue-tracker#392]
I've tried setting the compass directions in the theme, but they stop the try_move command from working.

Here's the output when the compass and compass_short are commented out

![image](https://user-images.githubusercontent.com/46803513/114390568-55147f00-9b8e-11eb-8416-a011fd45a376.png)

.. and with COMPASS uncommented...

![image](https://user-images.githubusercontent.com/46803513/114390730-87be7780-9b8e-11eb-99c0-48c348263f86.png)

It's the same with COMPASS_SHORT.

Here's the code which I use to pick up the directions...

![image](https://user-images.githubusercontent.com/46803513/114391051-ee439580-9b8e-11eb-9eea-306193aecdda.png)

At the end, I count the number of items added to the list, and if zero, I print out the nowhere command...
![image](https://user-images.githubusercontent.com/46803513/114391140-06b3b000-9b8f-11eb-8ea9-d80800ee7aec.png)

**Comment by ainslec** [comment]
Quickly found a bug to do with capitalization of compass directions.

Have you tried providing the compass directions using lower case?

**Comment by nww02** [comment]
I think I put them with capital names "Fore", "Aft", and so on...
