### ISSUE TITLE
[FEATURE - low priority]  treasure_room  functions

### ISSUE THREAD

**Issue by nww02** [ainslec/adventuron-issue-tracker#396]
There's a nice function is_at_initial_location which is great for figuring if something's been moved, but some games will calculate a score based on whether objects are at the treasure room or not, or (sometimes) being carried.

Is it possible to have a function:-

 * is_at_treasure_room( "object" ) 
 
which returns true when an object has been returned to the treasure room.

**Comment by ainslec** [comment]
Can you just use this?

`parent_of "object" == "treasure_room_id"`

**Comment by nww02** [comment]
Yep, I suppose that works too.   I just found it asymmetric that there was a command to see if treasure was where it started, but not one where it ended up...      That works just fine (and is how I'm doing it, sort of. :)

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by nww02** [comment]
I've used the parent_of "" that you suggested.  It works just fine. you can close this if you want.
