### ISSUE TITLE
Opening files does not work via the menu (beta 68j)

### ISSUE THREAD

**Issue by ainslec** [ainslec/adventuron-issue-tracker#401]
Opening a file is reported to fill the editor with weird characters.

Reported by Garry.

![image](https://user-images.githubusercontent.com/201870/114949171-51ac1c80-9e48-11eb-8aa3-094d7706bd8a.png)

**Comment by warrigal24** [comment]
I struck another example of this with another file. In this case, it had an error and a tooltip that may give a hint.

![adventuron-pink-dots](https://user-images.githubusercontent.com/76836466/115099097-165c3b80-9f77-11eb-9b43-7cc55e811964.png)

Farlander noted that if the file starts with a comment and you delete the comment using an external text editor prior to opening the file, the error goes away. This worked with both the files in the screen grabs. However, all my files start with a comment block and the error only occurs with some files.

**Comment by ainslec** [comment]
Fixed
