### ISSUE TITLE
[BUG]  reloading a save from a subroutine generated an error and failed.

### ISSUE THREAD

**Issue by nww02** [ainslec/adventuron-issue-tracker#402]
I started a new game and immediately hit "SAVE".

```

   :match "die _"
   {
      :gosub "restart_restore";
      :return;
  }


restart_restore : subroutine {
      :while(true)
      {
         :print "Which do you want to do, RESTART or RESTORE?";
         :set_string var="temp_str" {("")};
         :while (temp_str!= "restart" && temp_str != "restore")
         {
            :ask_string {
               question = 
               var = "temp_str"
            }
         }
         :if (temp_str == "restart"){
            :lose_game;
         }
         :if (temp_str == "restore"){
               :load;
               :set_string var="temp_str" {("")};   // catch a 'cancel' selection.
               :done;
         }
      }
   }
```

I then executed a command which ran a subroutine to trigger a LOAD to reload.  When I selected my savegame to reload, it generated the following errors:
![image](https://user-images.githubusercontent.com/46803513/115006839-3c171100-9ea1-11eb-81f9-ea8202d7c81b.png)

I've tried to recreate it in a 'clean' adventure, but there must be some construct I'm using that trips it, but that construct isn't in the sample game.

![image](https://user-images.githubusercontent.com/46803513/115013903-9025f380-9ea9-11eb-9b9f-b4111377982b.png)

**Comment by nww02** [comment]
Another way that it can fail:

![image](https://user-images.githubusercontent.com/46803513/115018044-4809cf80-9eaf-11eb-8a29-6eaa800c1e15.png)

**Comment by ainslec** [comment]
A very nice find.

**Comment by ainslec** [comment]
I don't know how you triggered the bug...

I built this standalone code to try to test it (using your code snipped), but I don't know what to do.

```
start_at = my_location

locations {
   my_location : location "You are in a room." ;
}

on_command {
   : match "test _"  {
      : gosub "restart_restore" ;
   }
}

strings {
   temp_str : string ;
}

subroutines {
   restart_restore : subroutine {
      :while(true) {
         :print "Which do you want to do, RESTART or RESTORE?";
         : clear "temp_str";

         :while (temp_str!= "restart" && temp_str != "restore")
         {
            :ask_string {
               question = 
               var = "temp_str"
            }
         }
         :if (temp_str == "restart"){
            : lose_game;
         }
         :if (temp_str == "restore"){
               : load ;
               : clear "temp_str";
               : done;
         }
      }
   }
}
```

**Comment by nww02** [comment]
All I do is just save a game and then type 'test' to reload the save game.  I'll be using that stub to add  stuff to try and force the error..

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by nww02** [comment]
Tested in 73f, and the restore works perfectly now!  All fixed!  Thank you :)
