### ISSUE TITLE
[FEATURE] Allow  the 'var' parameter to be a headline field

### ISSUE THREAD

**Issue by nww02** [ainslec/adventuron-issue-tracker#414]
Just to make things a little more consistent, is it possible to headline the 'var' parameter to the set_* functions.

In:
```
  :set_string var="some_string"   {("some_value")};
  :set_integer var="some_numer" {( some_value )};
 :set_boolean var="some_bool"  value="true";
```

, is it possible that the 'var' can be headlined so that you can do:-

```
  :set_string "some_string"   {("some_value")};
  :set_integer "some_numer" {( some_value )};
  :set_boolean "some_bool"  {("true")};
```

**Comment by ainslec** [comment]
Have a go.

**Comment by nww02** [comment]
Works perfectly!  Boy that compresses things down nicely!  Coupled with the {( )}  notation, it's getting much more streamlined!


Do you think it also makes sens to add the var field for other (lesser used) commands, such as "store_random"  to be headline fields as well?

________________________________

**Comment by ainslec** [comment]
"store_random" will allow a headline variant in an upcoming release.

Closing this issue. 

If you have any others to request a headline variant for, then use this issue without re-opening it.
