### ISSUE TITLE
[FEATURE] A "dark_graphic" location option and global switch.

### ISSUE THREAD

**Issue by nww02** [ainslec/adventuron-issue-tracker#418]
At the moment, when the "is_dark" expression evaluates to true, the header graphic is hidden.   In certain locations you may want to have a darkened spooky graphic when it's dark, or a "halo of light" around you when it's lit.  

Is it possible to add a setting to each room  "dark_graphic" which overrides the system default when the player is in that room and it's dark?

Is it also possible to add a setting to game_settings "show_default_location_graphic_when_dark"?  is can be 'false' by default.  When true, and the player is in a 'dark' place, the default room graphic is shown instead of the usual one, unless overridden by the location-specific "dark_graphic" option?

**Comment by ainslec** [comment]
Layout dynamic, if supplied will not omit graphic in dark mode unless required.

You can also override layouts at location level (though not at zone level yet).

```
my_location : location {
   layout_dynamic -> (is_dark ? "H G D O X" : "H G D O X")
}
```


```
theme_settings {
   layout_dynamic -> (is_dark ? "H G D O X" : "H G D O X")
}
```

**Comment by nww02** [comment]
That's a good way of keeping the image on-screen.

I guess by the same token you'd need to do

graphic->(is_dark ? "lit_room.png":"dark_room.png")

on all the locations.... Hmm.. messy, but workable.  Might be good to document that in the cookbook, I don't think many would intuit that.

thanks!

**Comment by ainslec** [comment]
Also consider use of this (at game_settings {} level):

```
game_settings {
   // Blank string is no default
   default_location_graphic -> (is_dark ? "my_dark_id" : "")
}
```

**Comment by nww02** [comment]
Hmm. would that work?   I thought that just set the default graphic, but the room graphic (if set) will override the default.

What I think probably would work (if it was permitted) would be:

my_location : location "Some place "  graphic-> ((is_dark)?"dark_room":"light_room");

I tried it, but the graphic parameter doesn't seem to permit code.



________________________________
