### ISSUE TITLE
Specific colour for text printed from "On Describe"

### ISSUE THREAD

**Issue by hnejfnvjojgrogjwm** [ainslec/adventuron-issue-tracker#44]
Is there a way to have a specific colour for the text printed after the description, from "On Describe"? If it is already there, I can’t find it.
Just like:
colors { 
         story_pen                      = #0cc
         header_pen                   = #fff
         paper                          = #212
         ...
         etc

I can do it manually using colour codes, so this has a low priority for me. But maybe there is already a code for this? Or maybe it is easy to implement?

**Comment by ainslec** [comment]
Away from keyboard now, but try incidental_pen = xxx

**Comment by hnejfnvjojgrogjwm** [comment]
incidental_pen works for the "On Tick" text, but not for "On Describe".

**Comment by ainslec** [comment]
I appears it was the only event category without its own pen.

I've added it in beta 34a as:
```
colors {
   embellishment_pen = ...
}
```

Let me know how it works out.

I'll document it later before I close this issue.

**Comment by hnejfnvjojgrogjwm** [comment]
Fixed. Please close the issue.

Note: On a side note, maybe trivial, embellishment_pen is not giving a clear clue of what kind of text is affecting. I would rather prefer something like "on_describe_pen".
