### ISSUE TITLE
Bug: The parser doesn't understand the command [UP + noun] for Spanish

### ISSUE THREAD

**Issue by hnejfnvjojgrogjwm** [ainslec/adventuron-issue-tracker#450]
```
//language=spanish

start_at = my_location

locations {
   my_location : location "You are near the tower and the hut." ;
   loc_tower : location "You are up the tower." ;
   loc_hut : location "You are inside the hut." ;
}

connections {
   from, direction, to = [
      my_location, up, loc_tower
      my_location, enter, loc_hut
   ]
}

vocabulary {
   :noun {aliases=[torre]}
}
```

-Please reproduce the provided code.
-Try moving around: UP and DOWN, ENTER and EXIT, UP THE TOWER and ENTER THE HUT
-Set the game language to Spanish
-Try the same thing: SUBIR and BAJAR, ENTRAR and SALIR, SUBIR TORRE and ENTRAR CABAÑA
-Observe that SUBIR TORRE (UP TOWER) doesn't work.

Please keep in mind that for Spanish language it is very common to use a noun after UP, even if it may sound awkward or unnecessary  in English.

**Comment by ainslec** [comment]
Fixed in beta 74e.
