### ISSUE TITLE
The loading screen is not showing in my game

### ISSUE THREAD

**Issue by hnejfnvjojgrogjwm** [ainslec/adventuron-issue-tracker#46]
Loading screen not showing ATM when is not uploaded in game but called from external link.
Code:
loading_screen: jpeg "http://roboscape.co.uk/onewebmedia/portada-v2.0small.jpg";

**Comment by hnejfnvjojgrogjwm** [comment]
Additional info: I tried with a .gif instead of a .jpg. The result is the same.

**Comment by ainslec** [comment]
This works for me:

```
start_at       = my_location
loading_screen = loading_screen

locations {
   my_location : location "You are in a room." ;
}

assets{
   graphics {
      loading_screen : jpeg "https://roboscape.co.uk/onewebmedia/portada-v2.0small.jpg";
   }
}
```

**Comment by hnejfnvjojgrogjwm** [comment]
OMG I am so sorry wasting your time with this. It was all my mistake. I didn't add the line:
loading_screen = loading_screen
Now it works. Please close.
BTW I ran a search for "loading_screen" in the manual and there is no reference.

**Comment by ainslec** [comment]
No problem, I'll add something to the document about the "loading_screen" setting.
