### ISSUE TITLE
NOUN2 needs to get fixed in dialogues,

### ISSUE THREAD

**Issue by hnejfnvjojgrogjwm** [ainslec/adventuron-issue-tracker#47]
NOUN2 needs to get fixed in dialogues, ATM is half fixed but still doing funny things. 
I can provide examples and code if necessary.

**Comment by hnejfnvjojgrogjwm** [comment]
Update: Before there was this problem that the game wont read correctly NOUN2 when you type something like: "SAY JIM HELLO" the game will not understand, but if you include a random character or word like "SAY JIM P HELLO" then the game understands.
I believe that was provisionally patched for Spanish (still not working for English). But in Spanish I have a funny issue when some NPC understands correctly what I type and another NPC still shows the old issues.
I tried to reproduce it in a new game made from scratch but it is not happening. I can provide the original code if necessary. I am going to check deeper into this issue.

**Comment by ainslec** [comment]
Please do provide sample code if you can.

**Comment by ainslec** [comment]
Is this still an issue?

**Comment by hnejfnvjojgrogjwm** [comment]
Sorry I totally forgot about this issue. I believe it was fixed long ago. Please close.
