### ISSUE TITLE
Suggestion to divide the manual in two

### ISSUE THREAD

**Issue by hnejfnvjojgrogjwm** [ainslec/adventuron-issue-tracker#48]
I find the manual quite big and includes some redundant content.

Once I have done the tutorials, I am not going to need them again, but every time I run a search it goes through the whole manual, tutorials included.

I think it may be a good idea to divide it into two (the Spanish version of PAWs was like that, I don't know about the original English one): A beginners manual with the introduction for new starters and the tutorials. And another manual with all the advanced concepts, lists of commands and references, for advanced users.

That way it will be easier to use for advanced users For example if I want to find some info about locations and connections and I run a search, I don't need to read again the many times when locations and connections are mentioned in the tutorials.

**Comment by ainslec** [comment]
Thanks. I completely understand this. It's developed into quite the monolith.

I'll look at splitting it somehow.

The main thing I think is taking out tutorial B (the in built tutorial), and linking to a seperate standalone html version of that from the user guide (which is the smaller tutorial plus all the reference material).

**Comment by ainslec** [comment]
I have split the user guide into 5 different files now:

* Top level User Guide + Reference Guide
* Tutorial A
* Tutorial B
* Cookbook
* 8-Bit Export Guide

The top level user guide is at the same URL:

https://adventuron.io/documentation, and I link to differerent HTML pages in the appropriate section.

It loads a lot faster now, looks less cluttered, and should reduce my web hosting overhead too (as the gifs were not configured to lazy load).
