### ISSUE TITLE
synonyms for TSTART/TSTOP?

### ISSUE THREAD

**Issue by andrewschultz** [ainslec/adventuron-issue-tracker#503]
I've tested a few Adventuron games and always get tripped up about the precise command for transcripts. People who review games sometimes like to leave transcripts, too, and a few didn't realize the command to get started.

TSTART/TSTOP is useful as something quick to type for inexperienced testers, but Inform and TADS both have TRANSCRIPT or TRANSCRIPT ON/OFF or SCRIPT. Is there any way to either

1) add these as synonyms or
2) allow the author to say "understand TRANSCRIPT ON as TSTARTing" to create these synonyms, or note this possibility in the docs at adventuron.io if it is already possible to do so?

**Comment by joshgoebel** [comment]
You should be able to add your own aliases... does calling TSTART and stop from a script not work?

**Comment by andrewschultz** [comment]
Josh, very belated thanks for this tip. I'm learning basic Adventuron so, yes, that'll be good for my own stuff.
