### ISSUE TITLE
Missing question mark in "Allow sound effects?" for Spanish

### ISSUE THREAD

**Issue by hnejfnvjojgrogjwm** [ainslec/adventuron-issue-tracker#510]
Steps to reproduce:
-Start a Spanish game for the first time.
-Observe the Spanish equivalent of "Allow sound effects?"
-The Spanish message is missing the opening question mark.

Actually reads:
Permitir efectos de sonido?

Please change to:
¿Permitir efectos de sonido?

**Comment by ainslec** [comment]
To be fixed in beta 78
