### ISSUE TITLE
Game is not loaded when the navigator has cookies disabled or blocked

### ISSUE THREAD

**Issue by paravaariar** [ainslec/adventuron-issue-tracker#515]
The player see no message of error (except in the navigator console in developer mode)

In Chrome: works in regular browsing, doesn't work in incognito (except if the user turn cookie blocker off)
In Edge: work is both regular window and private browsing

"an adventuron game also doesn't work in incognito in firefox, because firefox doesn't support IndexedDB in incognito ( https://bugzilla.mozilla.org/show_bug.cgi?id=781982 ). But it can be fixed by setting in about:config the parameter dom.indexedDB.privateBrowsing.enabled to true."

**Comment by ainslec** [comment]
Will be fixed in upcoming beta 78.
