### ISSUE TITLE
:set_subject1 doesn't work

### ISSUE THREAD

**Issue by ChristopherMerriner** [ainslec/adventuron-issue-tracker#518]
It would be nice if it did! This is an undocumented (secret?) function that, I think, should allow an object to be specified as subject1. But it doesn't work. In the below, GET APPLE should parse as GET BANANA, but debug_sentence reveals that doesn't happen:

```
start_at = my_location
locations {
   my_location : location "You are in a room.";
}
objects {
  apple : object "apple"at = "my_location" ;
      orange : object "orange"at = "my_location" ;
         banana: object "banana"at = "my_location" ;
            peach: object "peach"at = "my_location" ;
}
on_command {
: match "get apple"  {
   :set_subject1 "banana";
   :debug_sentence;
}
}
```

Output:

You are in a room.

You see apple, orange, banana and peach.

>GET APPLE

- PARSE RESULT -

verb : get (typed:get)

noun1 : apple (typed:apple)

- SCOPES -

universal1 : [apple]

known1 : [apple]

- SUBJECTS -

s1 : apple

s2 : unknown

You take apple.

**Comment by ainslec** [comment]
Will be fixed in upcoming beta 78.

**Comment by ChristopherMerriner** [comment]
Thanks Chris!
