### ISSUE TITLE
Feature Request: Please implement the equivalence of "u" and "ü"

### ISSUE THREAD

**Issue by hnejfnvjojgrogjwm** [ainslec/adventuron-issue-tracker#53]
Following the equivalency of á, é, í, ó, ú to a, e, i, o, u, please implement "ü" as equivalent of the regular "u".

**Comment by ainslec** [comment]
Can you copy and paste a snippet of where that character is not being deaccented properly, as in the code it should already be deaccented.

Unicode : \u00fc   ... https://unicodelookup.com/#0x00fc/1

**Comment by hnejfnvjojgrogjwm** [comment]
Sorry, my mistake. I was actually trying the opposite way, typing Müller when in the vocabulary is registered as Muller. The parser is not expected to do it the other way round, so this is not a bug, just me trying stupid things at 1am.
Please close.

**Comment by ainslec** [comment]
The best issues are non-issues :-)
