### ISSUE TITLE
Bug: Adjectives are only recognised if they go before the noun

### ISSUE THREAD

**Issue by hnejfnvjojgrogjwm** [ainslec/adventuron-issue-tracker#60]
Adventuron only identifies the match NOUN+ADJECTIVE when the adjective goes before the noun.

```
start_at = my_location

locations {
   my_location : location "You are in a room with Jim." ;}

on_command {

#  dialogues with npc
   : if (verb0_is "say" || noun0_is""==false){
      :gosub "sub_dialogues";
      :print "Who are you talking to?";
      :done;}
   }

subroutines {
   sub_dialogues:subroutine{

//talk to jim
   :if(noun0_is"jim"){
      :match"hello _"{
         :print"-Hi there.";
         :done;}
      :match"_ computer"{
         :if(adjective1_is"broken"){
            :print"-I will fix it.";
            :done;}}
      :cycle key="jim_says" predictable_order="true" skip_interval="0"{
         :print"-I don't understand";
         :print"-Excuse me?";
         :print"Please say again?";}
         :done;}
   }
}
```

Steps to reproduce:
1. Boot up the game
2. Type JIM THE COMPUTER IS BROKEN
3. Observe the result.
4. Type JIM BROKEN COMPUTER
5. Observe the result.

Please allow the adjectives to be in any position after or before the noun.

**Comment by hnejfnvjojgrogjwm** [comment]
I found a simple way around this, turning the adjective into a noun2. You can waive it or put it on hold if it is complicated to fix. For me it is not a problem any more. It is up to you.

**Comment by ainslec** [comment]
That's ok as a workaround in the very short term, but be aware this workaround in unstable whilst this issue remains open (resolution of this issue will necessarily break the workaround).

Please mark the areas in your code where you do this as "workaround" or "hack" as it's likely when this issue is resolved, that you will need to change your workaround and this will make those areas of code easier to find and change for future revisions of your game.

**Comment by hnejfnvjojgrogjwm** [comment]
I changed the dialogues system, the original one required of typing too complicated/long sentences. This is definitely not an issue any more. Please waive.

**Comment by ainslec** [comment]
Closing this without change.

**Comment by THEFARLANDER** [comment]
In spanish language, the adjective always goes after the noun, the opposite that in english language...

- llave roja, where [llave(key)] is the noun, and [roja(red)] is the adjective.
- llave verde, where [llave(key)] is the noun, and [verde(green)] is the adjective.

If there are two keys (llave roja[red key] y llave verde[green key]) and you type:
-Get llave roja
the answer is "be more specific" and the choose option. You have to type "Get roja llave" to get the red key, and this is no natural at spanish language....it is as if in english you would have to write "get key red"...it is not correct.
So it would be fine that the adjectives could be recognised after the noun, at least in spanish language.

**Comment by hnejfnvjojgrogjwm** [comment]
Farlander is very right, we need to switch the order of adjective and noun for the Spanish language.

**Comment by ainslec** [comment]
I confirm that adventuron assumes that the adjective comes before the noun, and this is not correct for Spanish language.

I'll be testing it (in the English language) with this code (this is for my reference):

```
start_at = my_location

locations {
   my_location : location "You are in a room." ;
}

objects {
   red_key   : object "a red key"   at = "my_location" ;
   green_key : object "a green key" at = "my_location" ;
}
```

**Comment by ainslec** [comment]
Please try (probable) fix in beta version (65a):

https://adventuron.io/beta

**Comment by hnejfnvjojgrogjwm** [comment]
Fixed. Now it works both ways, what is perfectly fine.

**Comment by THEFARLANDER** [comment]
Yes!. Great!
