### ISSUE TITLE
Manual: Misspelling mistake in Cookboock chapter 2.31 "very"

### ISSUE THREAD

**Issue by hnejfnvjojgrogjwm** [ainslec/adventuron-issue-tracker#61]
1. Cookboock
2. Chapter 2.31. Implementing A Safe
3. The text reads:
"Adventuron naturally tries to match inputs that the player enters against its vocabulary. There is one exception, and that is in the case of a **very** and a noun entered."

Result:
I bet that "very" should be a "verb".

**Comment by ainslec** [comment]
Fixed, it'll roll out as of next update.
