### ISSUE TITLE
Bug: Dialogues doesn't work properly when the prep "A" is used

### ISSUE THREAD

**Issue by hnejfnvjojgrogjwm** [ainslec/adventuron-issue-tracker#94]
In Spanish language the correct long version of SAY RANGER is the equivalent of SAY TO RANGER/ DECIR A RANGER. But if I introduce the preposition "A" between SAY and RANGER, the game doesn't understands. I even documented "A" as a preposition in the vocabulary but it didn't fix the issue. The name of the NPC is moved to NOUN1 as you can see in the screenshot.

![issue preposition](https://user-images.githubusercontent.com/65968239/85206607-33a28800-b31b-11ea-8337-e6c2846e9213.jpg)

**Comment by ainslec** [comment]
Please can you check this again using the beta version:

https://adventuron.io/beta

**Comment by hnejfnvjojgrogjwm** [comment]
I am experiencing the same issue.

**Comment by ainslec** [comment]
I made an update. Please try beta 48a.

I tested with:

```
start_at = lakeside

locations {
   lakeside : location "You are by the side of a lake.";
}

on_command {   
   : if (verb0_is "say" && noun0_is "jim" && noun1_is "hello") {
      : print "Hello" ;
   }
}
```

https://adventuron.io/beta

**Comment by hnejfnvjojgrogjwm** [comment]
Fixed. Please close.
